### ISSUE TITLE
[Bug]: The structure is synchronized, but the secondary partition is not synchronized.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2607] opened 2024-06-03 06:45 UTC
### ODC version

ODC430

### OB version

Oceanbase430 MYSQL

### What happened?

The structure is synchronized, but the secondary partition is not synchronized.
![image](https://github.com/oceanbase/odc/assets/59468957/16b247de-618a-48c2-9366-a0e293b84ed8)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

```
create table if not exists partrange_list_pri(
    col1 int,
    col2 numeric(10,2),            
    col3 decimal(10,2),       
    col4 bit(8),           
    col5 tinyint,           
    col6 smallint,          
    col7 mediumint,          
    col8 bigint,           
    col9 float(10,2),        
    col10 double(10,2),        
    col11 varchar(10),         
    col12 char(10),          
    col13 text,
    col14 tinytext,
    col15 mediumtext,
    col16 longtext,
    col17 blob,
    col18 tinyblob,
    clo19 longblob,
    col20 mediumblob,
    col21 binary(16),           
    col22 varbinary(16),           
    col23 timestamp,         
    col24 time,           
    col25 date,          
    col26 datetime,         
    col27 year,
    constraint pk_partrange_list_pri primary key(col1,col6)     
)partition by range(col6) subpartition by list(col1) subpartition template(
    subpartition p_1 values in (1),
    subpartition p_2 values in (2),
    subpartition p_3 values in (3),
    subpartition p_4 values in (4)
)
(
    partition p1 values less than(0),
    partition p2 values less than(10000),
    partition p3 values less than(100000),
    partition p4 values less than maxvalue
);
```

**Comment by guowl3** [comment] 2024-06-03 07:08
duplicate of [#2494](https://github.com/oceanbase/odc/issues/2494)

**Closed** 2024-06-03 08:19 UTC
Labels: type-bug, priority-medium, Issues found during testing
