### ISSUE TITLE
[Bug]: Create approval instance, server error

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1177] opened 2023-12-14 06:30 UTC
### ODC version

ODC423

### OB version

independent

### What happened?

Create approval instance, server error
![image](https://github.com/oceanbase/odc/assets/59468957/60663539-0caf-4625-a066-e8bd21be5140)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment] 2023-12-14 06:44
The cause is a front-end request parameter error:

**Comment by HSunboy** [comment] 2023-12-19 11:33
Fixed In Commit [43d4d0b7e67c2632e28b289f61da605386d56825](https://github.com/oceanbase/odc-client/commit/43d4d0b7e67c2632e28b289f61da605386d56825)
            ------
            陈朝俊
            Tue Dec 19 19:07:28 2023 +0800

**Closed by HSunboy** 2023-12-19 11:33 UTC
Labels: type-bug, priority-high

**Comment by sl01388797** [comment] 2023-12-20 07:04
![Image](https://github.com/oceanbase/odc/assets/143492234/308f58b2-cafd-4e31-9abc-c31efc42be4c)

pass
