### ISSUE TITLE
[Bug]: Proprietary cloud, result set output in CSV format to clipboard will be interrupted when encountering data of type binary

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#269] opened 2023-09-08 02:20 UTC
### ODC version

odc412

### OB version

ob410

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9828dd8e-305d-4a50-a4d2-2e1a08c41546)
![image](https://github.com/oceanbase/odc/assets/143492234/00e47a1e-788e-429e-9ab1-954cf51e32c8)
![image](https://github.com/oceanbase/odc/assets/143492234/b5856ed9-3081-4a7b-a7f8-e75c5dad9ce3)

### What did you expect to happen?

Output all content

### How can we reproduce it (as minimally and precisely as possible)?

Output binary data in CSV format

**Comment by sl01388797** [comment] 2024-06-05 02:12
![Image](https://github.com/oceanbase/odc/assets/143492234/15de6041-c359-451b-9796-ada25621f174)



![Image](https://github.com/oceanbase/odc/assets/143492234/c4d6ef9b-1d74-409c-985d-2fce0db27247)

The problem still exists

**Comment by HSunboy** [comment] 2024-06-05 09:55
It works for me. seems to be caused by the character limit of the clipboard

**Comment by HSunboy** [comment] 2024-07-09 02:56
https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%89%AA%E8%B4%B4%E6%9D%BF%E6%97%A0%E6%B3%95/772bca2a-2b45-4118-87d9-39a4b25d204b

**Comment by HSunboy** [comment] 2024-07-09 06:22
The Windows clipboard will automatically truncate when it encounters \u0000

**Comment by HSunboy** [comment] 2024-07-09 07:17
Fixed In Commit [4b20852d80af935c0b91278c2e94be0d90ca6f5b](https://github.com/oceanbase/odc-client/commit/4b20852d80af935c0b91278c2e94be0d90ca6f5b)
            ------
            xiaokang
            Tue Jul 9 15:10:42 2024 +0800

**Closed by HSunboy** 2024-07-09 07:17 UTC
Labels: type-bug, priority-medium, Issues found during testing

**Comment by sl01388797** [comment] 2024-07-15 06:20
![Image](https://github.com/user-attachments/assets/550647a5-6a89-4db3-8922-be7d03743fbb)

pass
