### ISSUE TITLE
[Bug]: Data cleaning task failed, log printing syntax error

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#645] opened 2023-10-27 08:12 UTC
### ODC version

ODC422

### OB version

it has nothing to do with ob version

### What happened?

Data cleaning task failed, log printing syntax error
![image](https://github.com/oceanbase/odc/assets/59468957/0bf79bda-a860-4336-b5ba-ca9e84b36e9e)
![image](https://github.com/oceanbase/odc/assets/59468957/f7197694-06b1-4ec1-b096-fafa9a44271c)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

See Private Cloud Environment

**Comment by guowl3** [comment] 2023-10-31 03:04
Compatibility issues caused by MYSQL 8.x are supported by DLM, and are expected to be fixed in SDK 1.0.5.

**Closed** 2023-12-12 11:27 UTC
Labels: type-bug, priority-medium
