### ISSUE TITLE
[Bug]:  When creating comments for the table, the statement generated by odc cannot be executed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#114] opened 2023-09-01 06:54 UTC
### ODC version

ODC420

### OB version

ob420
MYSQL

### What happened?

Connect to ob420 to execute the correct sql statement and report a syntax error

### What did you expect to happen?

able to execute

### How can we reproduce it (as minimally and precisely as possible)?

Connect to ob420, open the sql window
- When executing the following sql statement, a syntax error is reported

ALTER TABLE `piaoyue`.`consumer` MODIFY COLUMN `name` varchar CHARACTER SET gbk COLLATE gbk_chinese_ci COMMENT '啊啊啊' NULL;
![image](https://github.com/oceanbase/odc/assets/59468957/9f2e9630-ecba-42cb-a25b-41a89244370a)

ob410 is executed as follows
![image](https://github.com/oceanbase/odc/assets/59468957/630dd409-3b2a-4d1f-b9fb-f8bf93d3e008)

**Comment by Huangxiao-mas** [comment] 2023-09-01 07:09
Syntax error generated by odc

**Comment by Huangxiao-mas** [comment] 2023-09-01 07:39
![image](https://github.com/oceanbase/odc/assets/59468957/9dab7813-4109-4c53-9902-491b704071dd)

**Comment by yhilmare** [comment] 2023-09-01 07:42
@PeachThinking It looks like db-browser generated a wrong sql

**Comment by yhilmare** [comment] 2023-09-01 07:43
@Huangxiao-mas we suggest that one issue should be assigned to only one person

**Comment by Huangxiao-mas** [comment] 2023-09-01 07:45
> @Huangxiao-mas we suggest that one issue should be assigned to only one person
OK

**Comment by PeachThinking** [comment] 2023-09-04 06:48
The cause of this bug is: String data type like varchar do not hava presicion


![Image](https://github.com/oceanbase/odc/assets/140503120/bbcf57cb-737f-4f7c-966b-1fcfb2fee7ed)

This causes the generated SQL without accuracy `precision` like `varchar (45)`， odc 4.2.2 has fix this bug，see #82 
with precision the generated SQL would be：
```ALTER TABLE `piaoyue`.`consumer` MODIFY COLUMN `name` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci COMMENT 'test' NULL;```
 
Can you move the iteration of this bug to 4.2.2？ @Huangxiao-mas @yhilmare

**Comment by PeachThinking** [comment] 2023-09-04 07:12
4.2.2 has fix the bug，related pr：https://github.com/oceanbase/odc/pull/88

**Comment by sl01388797** [comment] 2023-10-30 06:58
![Image](https://github.com/oceanbase/odc/assets/143492234/7802aed8-5de2-4ded-8b62-4a595b6cd5f9)

pass

**Closed** 2023-10-31 06:29 UTC
Labels: type-bug, priority-medium
