### ISSUE TITLE
[Bug]: function or stored procedure list shows duplicate objects

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#527] opened 2023-10-17 06:20 UTC
### ODC version

ODC422

### OB version

OceanBase 4.1.0

### What happened?

Function or stored procedure list shows duplicate objects
![image](https://github.com/oceanbase/odc/assets/59468957/d086a607-aaf6-4cd5-9b29-79536250330d)
![image](https://github.com/oceanbase/odc/assets/59468957/52893efe-7798-4687-bb5f-51bc0e2887e7)

### What did you expect to happen?

display normally

### How can we reproduce it (as minimally and precisely as possible)?

See test environment

**Comment by yhilmare** [comment] 2023-10-18 06:55
this bug is caused by a observer's kernel bug, can not be fixed by odc

**Closed** 2023-10-18 08:27 UTC
Labels: type-bug, priority-high

**Comment by sl01388797** [comment] 2023-11-01 07:30
![Image](https://github.com/oceanbase/odc/assets/143492234/7300d1b1-f08c-44a3-ab29-5fd7bb511ab5)
![Image](https://github.com/oceanbase/odc/assets/143492234/2bcff873-8852-48e5-8261-c03b1749101a)
pass
