### ISSUE TITLE
[Bug]: Result sets cannot be downloaded from external tables

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3995] opened 2024-12-10 08:44 UTC
### ODC version

ODC 4.3.3

### OB version

OB4.3.2.1

### What happened?

Result sets cannot be downloaded from external tables
![图片](https://github.com/user-attachments/assets/dbdbf089-e8c3-4b3b-bc72-054acb62bf5c)

### What did you expect to happen?

Could download.

### How can we reproduce it (as minimally and precisely as possible)?

Download external result set

**Comment by zijiacj** [comment] 2024-12-12 03:05
it is caused by the sql window closing to download the result set configuration, and does not belong to the bug category

**Closed by zijiacj** 2024-12-12 03:05 UTC
Labels: type-bug, priority-medium, Issues found during testing, Pending add interface case

**Comment by sl01388797** [comment] 2024-12-31 08:20
![Image](https://github.com/user-attachments/assets/c52406b4-bcd2-415e-960c-2bc635bb3c91)
pass
