### ISSUE TITLE
[Bug]: Add unique constraints when there are too many columns to display the issue

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1593] opened 2024-02-22 03:06 UTC
### ODC version

odc424

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/31df2fbe-6c7c-40a8-8e32-b20285da457a

### What did you expect to happen?

*

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE `c` (
  `col` int(11) NOT NULL,
  `col1` int(11) DEFAULT NULL,
  `col11` int(12) DEFAULT NULL,
  `f` int(11) DEFAULT NULL,
  PRIMARY KEY (`col`),
  KEY `f` (`col1`) BLOCK_SIZE 16384 GLOBAL
)
2. Add a unique key constraint

**Comment by bluesky-xyh** [comment] 2024-03-29 08:07
Troubleshooting conclusion: The style problem does not recur under Mac, but it can happen under Windows. It can be inferred from the phenomenon that the problem should be caused by the horizontal scroll bar of the table container (when the drop-down selection box is expanded, if the height of the drop-down box is greater than the height of the table container, an issue will appear. vertical scroll bar)

**Comment by HSunboy** [comment] 2024-05-29 07:10
Fixed In Commit [f7f8d011871d36ed12c11e82f855ffdb65abccaf](https://github.com/oceanbase/odc-client/commit/f7f8d011871d36ed12c11e82f855ffdb65abccaf)
            ------
            xiaokang
            Wed May 29 14:58:29 2024 +0800

**Closed by HSunboy** 2024-05-29 07:10 UTC
Labels: type-bug, priority-medium, Issues found during testing

**Comment by sl01388797** [comment] 2024-05-30 06:18
![image](https://github.com/oceanbase/odc/assets/143492234/b4211a0d-82f5-4aab-af7d-d2fd2a9e6d6c)
pass
