### ISSUE TITLE
[Bug]: Metabase synchronization has been initiated continuously

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2767] opened 2024-06-18 08:03 UTC
### ODC version

odc430bp

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3f4626f5-84f0-4cbc-9bbb-1bd23f4c8e91)

### What did you expect to happen?

Metabase synchronization will not be initiated continuously

### How can we reproduce it (as minimally and precisely as possible)?

Enter link

**Comment by HSunboy** [comment] 2024-06-18 10:02
![Image](https://github.com/oceanbase/odc/assets/14886044/443671e3-c786-4c00-828e-9def0856f8c2)

status is PENDING

**Comment by smallsheeeep** [comment] 2024-06-24 03:01
The root cause is that some databases's sync status is PENDING, and at this time we restart the ODC server. Due to that ODC  will not create any new database sync task for these database which's status is PENDING, then these databases's sync status are always PENDING.

**Comment by HSunboy** [comment] 2024-07-04 08:34
@yhilmare This is not a front-end problem

**Comment by yhilmare** [comment] 2024-07-08 08:41
![68A4CB7B-5D5B-4412-842F-060B57790343](https://github.com/oceanbase/odc/assets/22992296/96d14841-6dcc-4c97-b752-272f8c49ea4c)

the data from the back end has been right, bug the front end is still sending request

**Comment by HSunboy** [comment] 2024-07-09 02:14
Fixed In Commit [7e9548985c9d1dae81911e06802b50444f4cd502](https://github.com/oceanbase/odc-client/commit/7e9548985c9d1dae81911e06802b50444f4cd502)
            ------
            畅晚
            Mon Jul 8 21:28:40 2024 +0800

**Comment by tonghan-gsh** [comment] 2024-07-30 12:13
![Image](https://github.com/user-attachments/assets/4b4ead5a-8133-4612-8aed-8cafbfd44da0)

pass

**Closed by tonghan-gsh** 2024-07-30 12:13 UTC
Labels: type-bug, priority-medium, Issues found during testing
